### ISSUE TITLE
Missing files in Vulkan Registry

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/Vulkan-Web-Registry#12]
The following files are missing:

| Resource                                                                                                                 | HTTP Status Code | Found on pages - Page                                                                                                       |
| :----------------------------------------------------------------------------------------------------------------------- | :--------------- | :-------------------------------------------------------------------------------------------------------------------------- |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH264RateControlStructureFlagsEXT.html | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h264.html                         |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH264RateControlStructureFlagsEXT.html | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h264.html                         |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH264RateControlStructureFlagsEXT.html | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH264RateControlStructureFlagBitsEXT.html |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_controls_v4_incompatibility.html     | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_float_controls.html                     |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkAllocationFunction_return_rules.html             | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkReallocationFunction.html                       |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionFlagsEXT.html                    | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_image_compression_control.html                 |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionFlagsEXT.html                    | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_image_compression_control.html                 |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionFlagsEXT.html                    | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionControlEXT.html                     |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionFlagsEXT.html                    | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionFlagBitsEXT.html                    |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionFlagsEXT.html                    | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCompressionPropertiesEXT.html                  |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH265RateControlStructureFlagsEXT.html | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h265.html                         |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH265RateControlStructureFlagsEXT.html | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h265.html                         |
| https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH265RateControlStructureFlagsEXT.html | 404 Not found    | https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkVideoEncodeH265RateControlStructureFlagBitsEXT.html |

**Comment by oddhack** [comment]
@outofcontrol is this issue coming from a crawler bot? I can fix some of these easily enough but some I can't find any links to from within the registry repository, and without knowing the source it will be hard to diagnose the problem. A few of them definitely *should* not exist.

**Comment by allcreatures** [comment]
The source page is in the 3rd column under 'Found on Pages'

**Comment by oddhack** [comment]
I'm not sure, but think these are addressed at this point. Closing the issue to clear the slate in this repository before switching over to KhronosGroup/Vulkan-Registry.
