### ISSUE TITLE
Vulkan library returns a NULL pointer for method vkGetDeviceProcAddr

### ISSUE THREAD

**Issue by bhomerTk** [KhronosGroup/Vulkan-Web-Registry#13]
File "/****/*****/Venv_vk/lib/python3.8/site-packages/vulkan/_vulkan.py", line 10282, in vkGetDeviceProcAddr
    raise ProcedureNotFoundError()
vulkan._vulkan.ProcedureNotFoundError

**Comment by oddhack** [comment]
This repo is just a publishing mechanism. I'm not sure which "Vulkan library" is involved but possibly you would want to raise this issue on the https://github.com/KhronosGroup/Vulkan-Loader/issues repository.
