### ISSUE TITLE
LoaderAndValidationLayers repo split into 4 separate repos. Need to update the Vulkan web registry

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Web-Registry#5]
The web page at https://www.khronos.org/registry/vulkan/ has references to the previously combined Vulkan LoaderAndValidationLayers repo. Could you update it to reference the new 4 separate repos instead?
1. KhronosGroup/Vulkan-headers
2. KhronosGroup/Vulkan-Tools
3. KhronosGroup/Vulkan-Loader
4. KhronosGroup/Vulkan-ValidationLayers

**Comment by oddhack** [comment]
Done.
