### ISSUE TITLE
Registry points to long out of date Vulkan headers

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/Vulkan-Web-Registry#6]
The registry section on Vulkan headers points you to Vulkan-Docs/include as the seemingly canonical place for headers. However the headers there are 5 months old and pre-date the split of vulkan.h into multiple headers.

The registry also suggests the Vulkan-Headers repo or the loader repo as possible sources. Vulkan-Headers is right up to date.

Either remove the headers from Vulkan-Docs and update the registry or else keep them up to date.

**Comment by oddhack** [comment]
The only files in include/vulkan are the static ones, and they haven't changed in a long time. The only time they would change is if there's a new Vulkan platform. We are not going to remove the static headers, that's where they belong.

The phrasing in the registry index page seems pretty clear to me, but I will attempt to be more pedantic shortly.
